language: python
python:
  - "3.6"
install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
before_script: 
  - mkdir biacpype/logs
script: 
  - pytest --cov=biacpype tests/
after_script: 
  - rm -rf biacpype/logs
after_success:
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: always
