language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install pytest pytest-cov
  - pip install coveralls
before_script: mkdir biacpype/logs
script: py.test
after_script: 
  - coveralls
  - rm -rf biacpype/logs
notifications:
  email:
    on_success: never
    on_failure: always
